propel:
  _attributes: {   package: plugins.sfAtosPaymentPlugin.lib.model }
  sf_atos_cart:
    _attributes: { phpName: sfAtosCart }
    id: ~
    # Prix en centimes
    amount: { type: integer, required: true, index: index } 
    # La valeur de ce champ est fournie par Mercanet au commerçant, lors de l’inscription de sa boutique
    merchant_id:  { type: varchar, size: 15, index: index, required: true }
    # Langue du commercant
    merchant_language: { type: varchar, size: 2, index: index }
    # Pays du commercant
    merchant_country: { type: varchar, size: 2, index: index }
    # Contient l’identifiant de la transaction de paiement. 
    transaction_id: { type: integer, size: 6, index: unique, required: true }
    # Contient le moyen de paiement choisi par l’internaute pour la transaction
    payment_means: { type: varchar, size: 128, index: index }
    # Champ interne renseigné par l’API, renvoyé dans la réponse et contenant la date
    # et l’heure GMT (Greenwich Mean Time) à laquelle l’API a été appelée par l’internaute
    # pour initialiser sa transaction. 
    transmission_date: { type: timestamp, required: true }
    # Fusion de payment_time et payment_date
    payment_time: { type: timestamp, index: index } 
    # Champ renvoyé dans la réponse et contenant le code de la réponse du serveur Mercanet. 
    response_code: { type: varchar, size: 2, index: index }
    # Champ renvoyé dans la réponse dans le cas d’une demande d’autorisation acceptée
    payment_certificate: { type: varchar, size: 12 }
    # Contient l’identifiant d’autorisation retourné par la banque si la demande d’autorisation est acceptée.
    # Ce champ est uniquement présent dans la réponse
    authorisation_id: { type: varchar, size: 10 } 
    # Code de la monnaie
    currency_code:  { type: integer, size: 3, index: index, required: true }
    # Ce champ n’est renseigné par le serveur Mercanet que si une demande d’autorisation a été réalisée
    card_number:  { type: varchar, size: 7 }
    # Champ renvoyé dans la réponse dans le cas d’un paiement avec une carte possédant un numéro de contrôle. 
    cvv_flag: { type: integer, size: 1, index: index }
    # Champ renvoyé dans la réponse dans le cas d’un paiement avec une carte possédant un numéro de contrôle
    cvv_response_code: { type: varchar, size: 2, index: index }
    # Champ renvoyé dans la réponse et contenant le code de la réponse du serveur d’autorisation bancaire.
    bank_response_code: { type: varchar, size: 2, index: index }
    # Champ renvoyé dans la réponse et contenant le code réponse complémentaire du serveur MERCANET. 
    complementary_code:  { type: varchar, size: 2, index: index }
    # Champ renvoyé dans la réponse et contenant une information
    # sur le  code réponse complémentaire du serveur MERCANET
    complementary_info: { type: varchar, size: 255 }
    # Ce champ peut être utilisé pour retrouver le contexte de la commande d’un acheteur. 
    return_context: { type: varchar, size: 256 }
    # Champ libre. Toute information transmise dans ce champ par le commerçant
    # lors de la requête de paiement est renvoyée dans la réponse sans modification.
    caddie: { type: longvarchar }
    # Langue de l'interface donc du client    
    language: { type: varchar, size: 2, index: index }
    # Ce champ est utilisé pour les paiements par abonnement.
    # ATTENTION : les caractères suivants « | », « ; », « : » et « " » sont interdits  
    customer_id:  { type: varchar, size: 19, index: index, required: true }
    # Contient le numéro de commande associé à la transaction de paiement. 
    # ATTENTION : les caractères suivants « | », « ; », « : » et  « " » sont interdits 
    order_id: { type: varchar, size: 32, index: unique }
    # Non utilisé par le serveur, peut contenir l’adresse mail de l’acheteur. 
    customer_email:  { type: varchar, size: 128, index: index }
    # Adresse ip du client
    customer_ip_address:  { type: varchar, size: 19, index: index }
    # Contient le nombre de jours avant l’envoi en banque de la transaction
    capture_day: { type: integer, size: 2, index: index }
    # Contient le mode d’envoi en banque de la transaction
    capture_mode: { type: varchar, size: 20, index: index }
    # Reponse complete
    data: { type: blob }