sf_atos_cart:
  columns:
    # Prix en centimes
    amount: { type: integer, notnull: true } 
    # La valeur de ce champ est fournie par Mercanet au commerçant, lors de l’inscription de sa boutique
    merchant_id:  { type: varchar(15), notnull: true }
    # Langue du commercant 
    merchant_language: { type: varchar(2) }
    # Pays du commercant
    merchant_country: { type: varchar(2) }
    # Contient l’identifiant de la transaction de paiement. 
    transaction_id: { type: integer(6), notnull: true }
    # Contient le moyen de paiement choisi par l’internaute pour la transaction
    payment_means: { type: varchar(128) }
    # Champ interne renseigné par l’API, renvoyé dans la réponse et contenant la date
    # et l’heure GMT (Greenwich Mean Time) à laquelle l’API a été appelée par l’internaute
    # pour initialiser sa transaction. 
    transmission_date: { type: timestamp, notnull: true }
    # Fusion de payment_time et payment_date
    payment_time: { type: timestamp } 
    # Champ renvoyé dans la réponse et contenant le code de la réponse du serveur Mercanet. 
    response_code: { type: varchar(2) }
    # Champ renvoyé dans la réponse dans le cas d’une demande d’autorisation acceptée
    payment_certificate: { type: varchar(12) }
    # Contient l’identifiant d’autorisation retourné par la banque si la demande d’autorisation est acceptée.
    # Ce champ est uniquement présent dans la réponse
    authorisation_id: { type: varchar(10) } 
    # Code de la monnaie
    currency_code:  { type: integer(3), notnull: true }
    # Ce champ n’est renseigné par le serveur Mercanet que si une demande d’autorisation a été réalisée
    card_number:  { type: varchar(7) }
    # Champ renvoyé dans la réponse dans le cas d’un paiement avec une carte possédant un numéro de contrôle. 
    cvv_flag: { type: integer(1) }
    # Champ renvoyé dans la réponse dans le cas d’un paiement avec une carte possédant un numéro de contrôle
    cvv_response_code: { type: varchar(2) }
    # Champ renvoyé dans la réponse et contenant le code de la réponse du serveur d’autorisation bancaire.
    bank_response_code: { type: varchar(2) }
    # Champ renvoyé dans la réponse et contenant le code réponse complémentaire du serveur MERCANET. 
    complementary_code:  { type: varchar(2) }
    # Champ renvoyé dans la réponse et contenant une information
    # sur le  code réponse complémentaire du serveur MERCANET
    complementary_info: { type: varchar(255) }
    # Ce champ peut être utilisé pour retrouver le contexte de la commande d’un acheteur. 
    return_context: { type: varchar(256) }
    # Champ libre. Toute information transmise dans ce champ par le commerçant
    # lors de la requête de paiement est renvoyée dans la réponse sans modification.
    caddie: { type: varchar(5000) }
    # Langue de l'interface donc du client    
    language: { type: varchar(2) }
    # Ce champ est utilisé pour les paiements par abonnement.
    # ATTENTION : les caractères suivants « | », « ; », « : » et « " » sont interdits  
    customer_id:  { type: varchar(19), notnull: true }
    # Contient le numéro de commande associé à la transaction de paiement. 
    # ATTENTION : les caractères suivants « | », « ; », « : » et  « " » sont interdits 
    order_id: { type: varchar(32), unique: true }
    # Non utilisé par le serveur, peut contenir l’adresse mail de l’acheteur. 
    customer_email:  { type: varchar(128) }
    # Adresse ip du client
    customer_ip_address:  { type: varchar(19) }
    # Contient le nombre de jours avant l’envoi en banque de la transaction
    capture_day: { type: integer(2) }
    # Contient le mode d’envoi en banque de la transaction
    capture_mode: { type: varchar(20) }
    # Reponse complete
    datas: { type: blob }
  indexes:
    amount:
      fields: [amount]
    merchant_id:
      fields: [merchant_id]
    merchant_country:
      fields: [merchant_country]
    merchant_language:
      fields: [merchant_language]
    payment_means:
      fields: [payment_means]
    payment_time:
      fields: [payment_time]
    response_code:
      fields: [response_code]
    currency_code:
      fields: [currency_code]
    cvv_flag:
      fields: [cvv_flag]
    cvv_response_code:
      fields: [cvv_response_code]
    bank_response_code:
      fields: [bank_response_code]
    language:
      fields: [language]
    customer_id:
      fields: [customer_id]
    customer_email:
      fields: [customer_email]
    customer_ip_address:
      fields: [customer_ip_address]
    capture_day:
      fields: [capture_day]
    capture_mode:
      fields: [capture_mode]
    
      
    